import type {
  AdminDealer,
  AdminKPI,
  ActivityEntry,
  AdminAnnouncement,
  TerritoryStats,
  MonthlyRevenue,
  ProductPerformance,
  MarketingAsset,
  DealerPromotion,
  MarketingCampaign,
  AdminOrder,
} from "./types";

/* ─── KPI Data ─── */

export const adminKPIs: AdminKPI[] = [
  { label: "Active Dealers", value: "8", change: 14.3, trend: "up" },
  { label: "Open Leads", value: "24", change: 8.2, trend: "up" },
  { label: "Monthly Revenue", value: "$342,800", change: 12.5, trend: "up" },
  { label: "Pending Orders", value: "12", change: -3.1, trend: "down" },
  { label: "Avg Order Value", value: "$4,218", change: 6.7, trend: "up" },
  { label: "Lead Conversion", value: "18.4%", change: 2.1, trend: "up" },
];

/* ─── Dealer Data ─── */

export const adminDealers: AdminDealer[] = [
  {
    id: "d1",
    name: "Premium Billiards",
    contactName: "Robert Chen",
    contactEmail: "robert@premiumbilliards.com",
    contactPhone: "281-351-4800",
    address: "14523 FM 2920",
    city: "Tomball",
    state: "TX",
    zip: "77377",
    phone: "281-351-4800",
    tier: "platinum",
    status: "active",
    joinDate: "2019-03-15",
    lastOrderDate: "2026-02-28",
    ytdRevenue: 128400,
    totalOrders: 34,
    territory: "Houston Metro",
  },
  {
    id: "d2",
    name: "Billiard Factory",
    contactName: "Marcus Williams",
    contactEmail: "marcus@billiardfactory.com",
    contactPhone: "713-681-8267",
    address: "10039 Northwest Fwy",
    city: "Houston",
    state: "TX",
    zip: "77092",
    phone: "713-681-8267",
    website: "https://billiardfactory.com",
    tier: "gold",
    status: "active",
    joinDate: "2020-06-01",
    lastOrderDate: "2026-03-02",
    ytdRevenue: 87200,
    totalOrders: 22,
    territory: "Houston Metro",
  },
  {
    id: "d3",
    name: "Qualty Billiards & Game Rooms",
    contactName: "David Foster",
    contactEmail: "david@qualtybilliards.com",
    contactPhone: "817-924-2653",
    address: "3500 S University Dr",
    city: "Fort Worth",
    state: "TX",
    zip: "76109",
    phone: "817-924-2653",
    tier: "silver",
    status: "active",
    joinDate: "2021-01-10",
    lastOrderDate: "2026-02-15",
    ytdRevenue: 54600,
    totalOrders: 14,
    territory: "DFW Metro",
  },
  {
    id: "d4",
    name: "Texas Billiards",
    contactName: "Sarah Mitchell",
    contactEmail: "sarah@texasbilliards.com",
    contactPhone: "512-454-2146",
    address: "8137 Mesa Dr",
    city: "Austin",
    state: "TX",
    zip: "78759",
    phone: "512-454-2146",
    website: "https://texasbilliards.com",
    tier: "gold",
    status: "active",
    joinDate: "2020-09-22",
    lastOrderDate: "2026-03-05",
    ytdRevenue: 92100,
    totalOrders: 19,
    territory: "Central Texas",
  },
  {
    id: "d5",
    name: "Peters Billiards",
    contactName: "James Peterson",
    contactEmail: "james@petersbilliards.com",
    contactPhone: "612-827-5958",
    address: "2940 Lyndale Ave S",
    city: "Minneapolis",
    state: "MN",
    zip: "55408",
    phone: "612-827-5958",
    website: "https://petersbilliards.com",
    tier: "silver",
    status: "active",
    joinDate: "2022-04-01",
    lastOrderDate: "2026-01-20",
    ytdRevenue: 41300,
    totalOrders: 11,
    territory: "Upper Midwest",
  },
  {
    id: "d6",
    name: "Best Buy Pool Supply",
    contactName: "Maria Rodriguez",
    contactEmail: "maria@bestbuypoolsupply.com",
    contactPhone: "602-955-6600",
    address: "2305 E Indian School Rd",
    city: "Phoenix",
    state: "AZ",
    zip: "85016",
    phone: "602-955-6600",
    tier: "bronze",
    status: "active",
    joinDate: "2023-08-15",
    lastOrderDate: "2026-02-10",
    ytdRevenue: 28700,
    totalOrders: 8,
    territory: "Southwest",
  },
  {
    id: "d7",
    name: "All Pro Billiards",
    contactName: "Thomas Burke",
    contactEmail: "thomas@allprobilliards.com",
    contactPhone: "781-942-7665",
    address: "7 Kimball Ln Unit C",
    city: "Lynnfield",
    state: "MA",
    zip: "01940",
    phone: "781-942-7665",
    website: "https://allprobilliards.com",
    tier: "silver",
    status: "active",
    joinDate: "2022-11-01",
    lastOrderDate: "2026-02-22",
    ytdRevenue: 38900,
    totalOrders: 10,
    territory: "Northeast",
  },
  {
    id: "d8",
    name: "Family Leisure",
    contactName: "Amanda Torres",
    contactEmail: "amanda@familyleisure.com",
    contactPhone: "972-416-4510",
    address: "1470 N. Stemmons Fwy",
    city: "Carrollton",
    state: "TX",
    zip: "75006",
    phone: "972-416-4510",
    website: "https://familyleisure.com",
    tier: "gold",
    status: "active",
    joinDate: "2021-05-20",
    lastOrderDate: "2026-03-01",
    ytdRevenue: 76500,
    totalOrders: 18,
    territory: "DFW Metro",
  },
];

/* ─── Activity Feed ─── */

export const recentActivity: ActivityEntry[] = [
  {
    id: "a1",
    type: "order",
    description: "New order #CLB-2026-0089 placed for 2x Elayna Pool Table",
    timestamp: "2026-03-09T10:30:00Z",
    dealerName: "Billiard Factory",
  },
  {
    id: "a2",
    type: "lead",
    description: "New lead captured: John Martinez, Houston TX, interested in Skylar",
    timestamp: "2026-03-09T09:15:00Z",
    dealerName: "Premium Billiards",
  },
  {
    id: "a3",
    type: "dealer",
    description: "Dealer tier upgraded from Silver to Gold",
    timestamp: "2026-03-08T16:45:00Z",
    dealerName: "Family Leisure",
  },
  {
    id: "a4",
    type: "order",
    description: "Order #CLB-2026-0087 shipped via freight carrier",
    timestamp: "2026-03-08T14:20:00Z",
    dealerName: "Texas Billiards",
  },
  {
    id: "a5",
    type: "warranty",
    description: "Warranty claim #WC-2026-012 resolved, replacement rail shipped",
    timestamp: "2026-03-08T11:00:00Z",
    dealerName: "Peters Billiards",
  },
  {
    id: "a6",
    type: "lead",
    description: "Lead converted to order: Catherine Wells, Scottsdale AZ",
    timestamp: "2026-03-07T15:30:00Z",
    dealerName: "Best Buy Pool Supply",
  },
  {
    id: "a7",
    type: "system",
    description: "Price list updated for Q2 2026, all dealers notified",
    timestamp: "2026-03-07T09:00:00Z",
  },
  {
    id: "a8",
    type: "order",
    description: "Order #CLB-2026-0085 entered production, est. 4 weeks",
    timestamp: "2026-03-06T13:45:00Z",
    dealerName: "All Pro Billiards",
  },
  {
    id: "a9",
    type: "dealer",
    description: "New dealer application received, pending review",
    timestamp: "2026-03-06T10:20:00Z",
  },
  {
    id: "a10",
    type: "lead",
    description: "5 new leads from trade show registration, assigned to territories",
    timestamp: "2026-03-05T17:00:00Z",
  },
];

/* ─── Announcements ─── */

export const adminAnnouncements: AdminAnnouncement[] = [
  {
    id: "ann1",
    title: "Q2 2026 Price Adjustments",
    body: "Effective April 1, select hardwood finishes will see a 3-5% adjustment. Updated price lists are available in the Downloads section. Contact your regional rep for volume pricing.",
    category: "pricing",
    status: "published",
    createdAt: "2026-03-01T09:00:00Z",
    publishedAt: "2026-03-01T09:00:00Z",
    targetAudience: "all",
  },
  {
    id: "ann2",
    title: "New Skylar Collection Launch",
    body: "The redesigned Skylar pool table is now available in three new finishes: Weathered Oak, Espresso, and Driftwood. Sell sheets and photography assets have been uploaded to the portal.",
    category: "product_update",
    status: "published",
    createdAt: "2026-02-20T10:00:00Z",
    publishedAt: "2026-02-22T08:00:00Z",
    targetAudience: "all",
  },
  {
    id: "ann3",
    title: "Platinum Dealer Exclusive: Early Access to 2027 Catalog",
    body: "Platinum tier dealers now have early access to the 2027 product catalog. Preview new collections and provide feedback before the official release.",
    category: "marketing",
    status: "published",
    createdAt: "2026-02-15T14:00:00Z",
    publishedAt: "2026-02-16T09:00:00Z",
    targetAudience: "platinum",
  },
  {
    id: "ann4",
    title: "Shipping Schedule Update: Spring 2026",
    body: "Due to increased demand, lead times for custom finish orders have extended to 6-8 weeks. Standard finishes remain at 3-4 weeks. Plan accordingly for spring deliveries.",
    category: "operations",
    status: "published",
    createdAt: "2026-02-10T11:00:00Z",
    publishedAt: "2026-02-10T11:00:00Z",
    targetAudience: "all",
  },
  {
    id: "ann5",
    title: "Summer Trade Show Schedule",
    body: "Draft announcement for upcoming summer trade show appearances and booth assignments.",
    category: "marketing",
    status: "draft",
    createdAt: "2026-03-08T16:00:00Z",
    targetAudience: "all",
  },
];

/* ─── Analytics: Territory Performance ─── */

export const territoryStats: TerritoryStats[] = [
  { territory: "Houston Metro", dealerCount: 2, totalRevenue: 215600, avgOrderValue: 3850, leadCount: 8, conversionRate: 22.5 },
  { territory: "DFW Metro", dealerCount: 2, totalRevenue: 131100, avgOrderValue: 4097, leadCount: 6, conversionRate: 16.7 },
  { territory: "Central Texas", dealerCount: 1, totalRevenue: 92100, avgOrderValue: 4847, leadCount: 4, conversionRate: 25.0 },
  { territory: "Upper Midwest", dealerCount: 1, totalRevenue: 41300, avgOrderValue: 3754, leadCount: 3, conversionRate: 13.3 },
  { territory: "Southwest", dealerCount: 1, totalRevenue: 28700, avgOrderValue: 3588, leadCount: 2, conversionRate: 10.0 },
  { territory: "Northeast", dealerCount: 1, totalRevenue: 38900, avgOrderValue: 3890, leadCount: 1, conversionRate: 20.0 },
];

/* ─── Analytics: Monthly Revenue ─── */

export const monthlyRevenue: MonthlyRevenue[] = [
  { month: "Oct", revenue: 248000 },
  { month: "Nov", revenue: 312000 },
  { month: "Dec", revenue: 286000 },
  { month: "Jan", revenue: 298000 },
  { month: "Feb", revenue: 321000 },
  { month: "Mar", revenue: 342800 },
];

/* ─── Analytics: Product Performance ─── */

export const productPerformance: ProductPerformance[] = [
  { name: "Skylar", category: "Pool Tables", unitsSold: 42, revenue: 188400 },
  { name: "Elayna", category: "Pool Tables", unitsSold: 38, revenue: 171000 },
  { name: "Addison", category: "Pool Tables", unitsSold: 28, revenue: 112000 },
  { name: "Dutchess", category: "Pool Tables", unitsSold: 22, revenue: 99000 },
  { name: "Piston", category: "Shuffleboards", unitsSold: 15, revenue: 67500 },
  { name: "Skylar Cue Rack", category: "Cue Racks", unitsSold: 35, revenue: 24500 },
  { name: "Hartford Cue Rack", category: "Cue Racks", unitsSold: 28, revenue: 19600 },
  { name: "Premium Ball Set", category: "Accessories", unitsSold: 64, revenue: 12800 },
];

/* ─── Marketing: Sales Enablement Assets ─── */

export const marketingAssets: MarketingAsset[] = [
  {
    id: "ma1",
    name: "Skylar Collection Sell Sheet",
    description: "Two-page sell sheet featuring the redesigned Skylar pool table in all available finishes.",
    category: "sell_sheet",
    filename: "skylar-sell-sheet-2026.pdf",
    fileType: "pdf",
    fileSizeKb: 2400,
    status: "active",
    version: "2.1",
    uploadedAt: "2026-02-18T10:00:00Z",
    updatedAt: "2026-02-22T14:30:00Z",
    downloads: 142,
    targetTier: "all",
  },
  {
    id: "ma2",
    name: "2026 Full Product Catalog",
    description: "Complete product catalog with all pool tables, shuffleboards, cue racks, and accessories.",
    category: "catalog",
    filename: "clb-2026-catalog.pdf",
    fileType: "pdf",
    fileSizeKb: 18500,
    status: "active",
    version: "1.0",
    uploadedAt: "2026-01-15T09:00:00Z",
    updatedAt: "2026-01-15T09:00:00Z",
    downloads: 98,
    targetTier: "all",
  },
  {
    id: "ma3",
    name: "Brand Guidelines",
    description: "Official CLB brand guidelines including logo usage, color palette, typography, and photography standards.",
    category: "brand_guide",
    filename: "clb-brand-guidelines.pdf",
    fileType: "pdf",
    fileSizeKb: 5200,
    status: "active",
    version: "3.0",
    uploadedAt: "2025-11-01T10:00:00Z",
    updatedAt: "2026-01-10T11:00:00Z",
    downloads: 87,
    targetTier: "all",
  },
  {
    id: "ma4",
    name: "Elayna Pool Table Sell Sheet",
    description: "Product sell sheet for the Elayna pool table with pricing, specs, and lifestyle photography.",
    category: "sell_sheet",
    filename: "elayna-sell-sheet-2026.pdf",
    fileType: "pdf",
    fileSizeKb: 1800,
    status: "active",
    version: "1.2",
    uploadedAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-02-05T09:00:00Z",
    downloads: 76,
    targetTier: "all",
  },
  {
    id: "ma5",
    name: "Spring 2026 Campaign Kit",
    description: "Digital ad templates, social media assets, and email templates for the spring season push.",
    category: "campaign_kit",
    filename: "spring-2026-campaign-kit.zip",
    fileType: "zip",
    fileSizeKb: 34200,
    status: "active",
    version: "1.0",
    uploadedAt: "2026-02-25T10:00:00Z",
    updatedAt: "2026-02-25T10:00:00Z",
    downloads: 34,
    targetTier: "gold",
  },
  {
    id: "ma6",
    name: "Showroom Photography Pack",
    description: "High-resolution lifestyle and studio photography for showroom displays and local advertising.",
    category: "showroom",
    filename: "clb-showroom-photos-2026.zip",
    fileType: "zip",
    fileSizeKb: 128000,
    status: "active",
    version: "1.0",
    uploadedAt: "2026-01-05T10:00:00Z",
    updatedAt: "2026-01-05T10:00:00Z",
    downloads: 52,
    targetTier: "all",
  },
  {
    id: "ma7",
    name: "Q2 2026 MSRP Price List",
    description: "Updated dealer pricing for all products effective April 1, 2026.",
    category: "price_list",
    filename: "clb-price-list-q2-2026.pdf",
    fileType: "pdf",
    fileSizeKb: 420,
    status: "active",
    version: "1.0",
    uploadedAt: "2026-03-01T09:00:00Z",
    updatedAt: "2026-03-01T09:00:00Z",
    downloads: 61,
    targetTier: "all",
  },
  {
    id: "ma8",
    name: "Duke Shuffleboard Sell Sheet",
    description: "Sell sheet for the Duke shuffleboard with dimensions, finishes, and feature highlights.",
    category: "sell_sheet",
    filename: "duke-shuffleboard-sell-sheet.pdf",
    fileType: "pdf",
    fileSizeKb: 1600,
    status: "active",
    version: "1.0",
    uploadedAt: "2026-02-10T10:00:00Z",
    updatedAt: "2026-02-10T10:00:00Z",
    downloads: 29,
    targetTier: "all",
  },
  {
    id: "ma9",
    name: "Fall 2026 Preview Catalog",
    description: "Early look at upcoming fall collections. Pending photography and final pricing.",
    category: "catalog",
    filename: "clb-fall-2026-preview.pdf",
    fileType: "pdf",
    fileSizeKb: 8400,
    status: "draft",
    version: "0.1",
    uploadedAt: "2026-03-05T16:00:00Z",
    updatedAt: "2026-03-05T16:00:00Z",
    downloads: 0,
    targetTier: "platinum",
  },
];

/* ─── Marketing: Promotions ─── */

export const dealerPromotions: DealerPromotion[] = [
  {
    id: "p1",
    title: "Spring Floor Model Incentive",
    description: "Receive a $300 spiff for each new CLB floor model placed in your showroom between March and May. Minimum 2 models required.",
    type: "spiff",
    status: "active",
    startDate: "2026-03-01",
    endDate: "2026-05-31",
    eligibleTiers: ["platinum", "gold"],
    eligibleProducts: ["all"],
    incentiveValue: "$300 per floor model",
    redemptions: 6,
    maxRedemptions: 24,
    createdAt: "2026-02-20T10:00:00Z",
  },
  {
    id: "p2",
    title: "Q2 Volume Discount",
    description: "5% discount on orders of 10 or more units placed during Q2. Applies to all pool table and shuffleboard models.",
    type: "volume_discount",
    status: "active",
    startDate: "2026-04-01",
    endDate: "2026-06-30",
    eligibleTiers: ["platinum", "gold", "silver", "bronze"],
    eligibleProducts: ["all"],
    incentiveValue: "5% off 10+ units",
    redemptions: 0,
    maxRedemptions: null,
    createdAt: "2026-03-01T09:00:00Z",
  },
  {
    id: "p3",
    title: "Skylar Launch Co-Op Program",
    description: "50% co-op funding on digital advertising featuring the new Skylar collection. Pre-approved ad templates available in the campaign kit.",
    type: "co_op",
    status: "active",
    startDate: "2026-02-22",
    endDate: "2026-06-30",
    eligibleTiers: ["platinum", "gold"],
    eligibleProducts: ["skylar"],
    incentiveValue: "50% co-op on digital ads",
    redemptions: 4,
    maxRedemptions: 16,
    createdAt: "2026-02-15T10:00:00Z",
  },
  {
    id: "p4",
    title: "Summer Showroom Refresh Rebate",
    description: "Up to $1,000 rebate for dealers who refresh their CLB showroom display with current-year models before summer selling season.",
    type: "seasonal_rebate",
    status: "scheduled",
    startDate: "2026-06-01",
    endDate: "2026-08-31",
    eligibleTiers: ["platinum", "gold", "silver"],
    eligibleProducts: ["all"],
    incentiveValue: "Up to $1,000 rebate",
    redemptions: 0,
    maxRedemptions: 12,
    createdAt: "2026-03-05T10:00:00Z",
  },
  {
    id: "p5",
    title: "2025 Year-End Closeout",
    description: "15% discount on remaining 2025 inventory. Limited to in-stock items only.",
    type: "seasonal_rebate",
    status: "expired",
    startDate: "2025-11-15",
    endDate: "2025-12-31",
    eligibleTiers: ["platinum", "gold", "silver", "bronze"],
    eligibleProducts: ["all"],
    incentiveValue: "15% off 2025 inventory",
    redemptions: 18,
    maxRedemptions: null,
    createdAt: "2025-11-01T10:00:00Z",
  },
];

/* ─── Marketing: Campaigns ─── */

export const marketingCampaigns: MarketingCampaign[] = [
  {
    id: "c1",
    name: "Spring 2026 Dealer Email Series",
    description: "Four-part email series showcasing new Skylar finishes, spring promotions, and co-op opportunities. Sent bi-weekly through April.",
    channel: "email",
    status: "active",
    startDate: "2026-03-01",
    endDate: "2026-04-30",
    targetTiers: ["platinum", "gold", "silver", "bronze"],
    dealersReached: 8,
    leadsGenerated: 12,
    budget: 1200,
    spent: 480,
    createdAt: "2026-02-20T10:00:00Z",
  },
  {
    id: "c2",
    name: "DFW Home & Patio Show 2026",
    description: "CLB booth at the DFW Home & Patio Show. Featuring Skylar and Elayna models with interactive configurator demo.",
    channel: "trade_show",
    status: "planning",
    startDate: "2026-05-15",
    endDate: "2026-05-18",
    targetTiers: ["platinum", "gold"],
    dealersReached: 0,
    leadsGenerated: 0,
    budget: 8000,
    spent: 2400,
    createdAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "c3",
    name: "Skylar Launch Digital Push",
    description: "Co-op funded digital ad campaign across dealer markets promoting the redesigned Skylar collection.",
    channel: "co_op_digital",
    status: "completed",
    startDate: "2026-02-22",
    endDate: "2026-03-07",
    targetTiers: ["platinum", "gold"],
    dealersReached: 4,
    leadsGenerated: 18,
    budget: 6000,
    spent: 5200,
    createdAt: "2026-02-18T10:00:00Z",
  },
  {
    id: "c4",
    name: "Q1 Direct Mail: New Catalog",
    description: "Physical catalog mailer sent to all active dealers with personalized cover letter from the CLB team.",
    channel: "direct_mail",
    status: "completed",
    startDate: "2026-01-15",
    endDate: "2026-01-31",
    targetTiers: ["platinum", "gold", "silver", "bronze"],
    dealersReached: 8,
    leadsGenerated: 3,
    budget: 2400,
    spent: 2150,
    createdAt: "2026-01-10T10:00:00Z",
  },
  {
    id: "c5",
    name: "Social Media Co-Op Templates",
    description: "Dealer-branded social media templates for Instagram and Facebook. Ongoing program with quarterly content refresh.",
    channel: "social",
    status: "active",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    targetTiers: ["platinum", "gold", "silver"],
    dealersReached: 6,
    leadsGenerated: 8,
    budget: 3600,
    spent: 900,
    createdAt: "2025-12-15T10:00:00Z",
  },
];

/* ─── Order Management ─── */

export const adminOrders: AdminOrder[] = [
  {
    id: "o1",
    orderNumber: "CLB-2026-0089",
    dealerId: "d2",
    dealerName: "Billiard Factory",
    status: "submitted",
    createdDate: "2026-03-09",
    updatedDate: "2026-03-09",
    itemCount: 2,
    productSummary: "2x Elayna Pool Table (Espresso)",
    subtotal: 9000,
    shipping: 480,
    total: 9480,
    customerName: "David Patterson",
    territory: "Houston Metro",
    eta: null,
    trackingNumber: null,
    carrier: null,
  },
  {
    id: "o2",
    orderNumber: "CLB-2026-0088",
    dealerId: "d4",
    dealerName: "Texas Billiards",
    status: "confirmed",
    createdDate: "2026-03-07",
    updatedDate: "2026-03-08",
    itemCount: 1,
    productSummary: "1x Skylar Pool Table (Weathered Oak) + Cue Rack",
    subtotal: 5800,
    shipping: 320,
    total: 6120,
    customerName: "Lisa Chen",
    territory: "Central Texas",
    eta: "2026-04-05",
    trackingNumber: null,
    carrier: "Freight Carrier",
  },
  {
    id: "o3",
    orderNumber: "CLB-2026-0087",
    dealerId: "d4",
    dealerName: "Texas Billiards",
    status: "shipped",
    createdDate: "2026-03-02",
    updatedDate: "2026-03-08",
    itemCount: 1,
    productSummary: "1x Addison Pool Table (Charcoal)",
    subtotal: 4200,
    shipping: 280,
    total: 4480,
    customerName: "Mark Stevens",
    territory: "Central Texas",
    eta: "2026-03-12",
    trackingNumber: "1Z999AA10123456784",
    carrier: "UPS Freight",
  },
  {
    id: "o4",
    orderNumber: "CLB-2026-0086",
    dealerId: "d1",
    dealerName: "Premium Billiards",
    status: "in_production",
    createdDate: "2026-02-28",
    updatedDate: "2026-03-05",
    itemCount: 3,
    productSummary: "2x Skylar Pool Table (Driftwood), 1x Piston Shuffleboard",
    subtotal: 14200,
    shipping: 640,
    total: 14840,
    customerName: "Floor Stock",
    territory: "Houston Metro",
    eta: "2026-03-28",
    trackingNumber: null,
    carrier: null,
  },
  {
    id: "o5",
    orderNumber: "CLB-2026-0085",
    dealerId: "d7",
    dealerName: "All Pro Billiards",
    status: "in_production",
    createdDate: "2026-02-22",
    updatedDate: "2026-03-06",
    itemCount: 2,
    productSummary: "1x Dutchess Pool Table (Natural), 1x Hartford Cue Rack",
    subtotal: 5400,
    shipping: 380,
    total: 5780,
    customerName: "James O'Brien",
    territory: "Northeast",
    eta: "2026-03-22",
    trackingNumber: null,
    carrier: null,
  },
  {
    id: "o6",
    orderNumber: "CLB-2026-0084",
    dealerId: "d8",
    dealerName: "Family Leisure",
    status: "shipped",
    createdDate: "2026-02-18",
    updatedDate: "2026-03-03",
    itemCount: 2,
    productSummary: "2x Elayna Pool Table (Natural Oak)",
    subtotal: 9000,
    shipping: 480,
    total: 9480,
    customerName: "Rachel Kim",
    territory: "DFW Metro",
    eta: "2026-03-10",
    trackingNumber: "PRO-7829451",
    carrier: "ABF Freight",
  },
  {
    id: "o7",
    orderNumber: "CLB-2026-0083",
    dealerId: "d3",
    dealerName: "Qualty Billiards & Game Rooms",
    status: "delivered",
    createdDate: "2026-02-10",
    updatedDate: "2026-02-28",
    itemCount: 1,
    productSummary: "1x Skylar Pool Table (Espresso)",
    subtotal: 4800,
    shipping: 280,
    total: 5080,
    customerName: "Anthony Garcia",
    territory: "DFW Metro",
    eta: null,
    trackingNumber: "1Z999AA10123456780",
    carrier: "UPS Freight",
  },
  {
    id: "o8",
    orderNumber: "CLB-2026-0082",
    dealerId: "d5",
    dealerName: "Peters Billiards",
    status: "delivered",
    createdDate: "2026-02-05",
    updatedDate: "2026-02-24",
    itemCount: 1,
    productSummary: "1x Piston Shuffleboard (Weathered Oak)",
    subtotal: 4500,
    shipping: 420,
    total: 4920,
    customerName: "Sarah Lindstrom",
    territory: "Upper Midwest",
    eta: null,
    trackingNumber: "PRO-7812093",
    carrier: "ABF Freight",
  },
  {
    id: "o9",
    orderNumber: "CLB-2026-0081",
    dealerId: "d6",
    dealerName: "Best Buy Pool Supply",
    status: "in_production",
    createdDate: "2026-02-15",
    updatedDate: "2026-03-01",
    itemCount: 1,
    productSummary: "1x Addison Pool Table (Natural) + Premium Ball Set",
    subtotal: 4400,
    shipping: 320,
    total: 4720,
    customerName: "Carlos Mendez",
    territory: "Southwest",
    eta: "2026-03-18",
    trackingNumber: null,
    carrier: null,
  },
  {
    id: "o10",
    orderNumber: "CLB-2026-0080",
    dealerId: "d1",
    dealerName: "Premium Billiards",
    status: "submitted",
    createdDate: "2026-03-08",
    updatedDate: "2026-03-08",
    itemCount: 4,
    productSummary: "3x Skylar Cue Rack (Espresso), 1x Hartford Cue Rack (Natural)",
    subtotal: 3200,
    shipping: 180,
    total: 3380,
    customerName: "Floor Stock",
    territory: "Houston Metro",
    eta: null,
    trackingNumber: null,
    carrier: null,
  },
];
