import type {
  AdminDealer,
  AdminKPI,
  ActivityEntry,
  AdminAnnouncement,
  TerritoryStats,
  MonthlyRevenue,
  ProductPerformance,
} from "./types";

/* ─── KPI Data ─── */

export const adminKPIs: AdminKPI[] = [
  { label: "Active Dealers", value: "8", change: 14.3, trend: "up" },
  { label: "Open Leads", value: "24", change: 8.2, trend: "up" },
  { label: "Monthly Revenue", value: "$342,800", change: 12.5, trend: "up" },
  { label: "Pending Orders", value: "12", change: -3.1, trend: "down" },
  { label: "Avg Order Value", value: "$4,218", change: 6.7, trend: "up" },
  { label: "Lead Conversion", value: "18.4%", change: 2.1, trend: "up" },
];

/* ─── Dealer Data ─── */

export const adminDealers: AdminDealer[] = [
  {
    id: "d1",
    name: "Premium Billiards",
    contactName: "Robert Chen",
    contactEmail: "robert@premiumbilliards.com",
    contactPhone: "281-351-4800",
    address: "14523 FM 2920",
    city: "Tomball",
    state: "TX",
    zip: "77377",
    phone: "281-351-4800",
    tier: "platinum",
    status: "active",
    joinDate: "2019-03-15",
    lastOrderDate: "2026-02-28",
    ytdRevenue: 128400,
    totalOrders: 34,
    territory: "Houston Metro",
  },
  {
    id: "d2",
    name: "Billiard Factory",
    contactName: "Marcus Williams",
    contactEmail: "marcus@billiardfactory.com",
    contactPhone: "713-681-8267",
    address: "10039 Northwest Fwy",
    city: "Houston",
    state: "TX",
    zip: "77092",
    phone: "713-681-8267",
    website: "https://billiardfactory.com",
    tier: "gold",
    status: "active",
    joinDate: "2020-06-01",
    lastOrderDate: "2026-03-02",
    ytdRevenue: 87200,
    totalOrders: 22,
    territory: "Houston Metro",
  },
  {
    id: "d3",
    name: "Qualty Billiards & Game Rooms",
    contactName: "David Foster",
    contactEmail: "david@qualtybilliards.com",
    contactPhone: "817-924-2653",
    address: "3500 S University Dr",
    city: "Fort Worth",
    state: "TX",
    zip: "76109",
    phone: "817-924-2653",
    tier: "silver",
    status: "active",
    joinDate: "2021-01-10",
    lastOrderDate: "2026-02-15",
    ytdRevenue: 54600,
    totalOrders: 14,
    territory: "DFW Metro",
  },
  {
    id: "d4",
    name: "Texas Billiards",
    contactName: "Sarah Mitchell",
    contactEmail: "sarah@texasbilliards.com",
    contactPhone: "512-454-2146",
    address: "8137 Mesa Dr",
    city: "Austin",
    state: "TX",
    zip: "78759",
    phone: "512-454-2146",
    website: "https://texasbilliards.com",
    tier: "gold",
    status: "active",
    joinDate: "2020-09-22",
    lastOrderDate: "2026-03-05",
    ytdRevenue: 92100,
    totalOrders: 19,
    territory: "Central Texas",
  },
  {
    id: "d5",
    name: "Peters Billiards",
    contactName: "James Peterson",
    contactEmail: "james@petersbilliards.com",
    contactPhone: "612-827-5958",
    address: "2940 Lyndale Ave S",
    city: "Minneapolis",
    state: "MN",
    zip: "55408",
    phone: "612-827-5958",
    website: "https://petersbilliards.com",
    tier: "silver",
    status: "active",
    joinDate: "2022-04-01",
    lastOrderDate: "2026-01-20",
    ytdRevenue: 41300,
    totalOrders: 11,
    territory: "Upper Midwest",
  },
  {
    id: "d6",
    name: "Best Buy Pool Supply",
    contactName: "Maria Rodriguez",
    contactEmail: "maria@bestbuypoolsupply.com",
    contactPhone: "602-955-6600",
    address: "2305 E Indian School Rd",
    city: "Phoenix",
    state: "AZ",
    zip: "85016",
    phone: "602-955-6600",
    tier: "bronze",
    status: "active",
    joinDate: "2023-08-15",
    lastOrderDate: "2026-02-10",
    ytdRevenue: 28700,
    totalOrders: 8,
    territory: "Southwest",
  },
  {
    id: "d7",
    name: "All Pro Billiards",
    contactName: "Thomas Burke",
    contactEmail: "thomas@allprobilliards.com",
    contactPhone: "781-942-7665",
    address: "7 Kimball Ln Unit C",
    city: "Lynnfield",
    state: "MA",
    zip: "01940",
    phone: "781-942-7665",
    website: "https://allprobilliards.com",
    tier: "silver",
    status: "active",
    joinDate: "2022-11-01",
    lastOrderDate: "2026-02-22",
    ytdRevenue: 38900,
    totalOrders: 10,
    territory: "Northeast",
  },
  {
    id: "d8",
    name: "Family Leisure",
    contactName: "Amanda Torres",
    contactEmail: "amanda@familyleisure.com",
    contactPhone: "972-416-4510",
    address: "1470 N. Stemmons Fwy",
    city: "Carrollton",
    state: "TX",
    zip: "75006",
    phone: "972-416-4510",
    website: "https://familyleisure.com",
    tier: "gold",
    status: "active",
    joinDate: "2021-05-20",
    lastOrderDate: "2026-03-01",
    ytdRevenue: 76500,
    totalOrders: 18,
    territory: "DFW Metro",
  },
];

/* ─── Activity Feed ─── */

export const recentActivity: ActivityEntry[] = [
  {
    id: "a1",
    type: "order",
    description: "New order #CLB-2026-0089 placed for 2x Elayna Pool Table",
    timestamp: "2026-03-09T10:30:00Z",
    dealerName: "Billiard Factory",
  },
  {
    id: "a2",
    type: "lead",
    description: "New lead captured: John Martinez, Houston TX, interested in Skylar",
    timestamp: "2026-03-09T09:15:00Z",
    dealerName: "Premium Billiards",
  },
  {
    id: "a3",
    type: "dealer",
    description: "Dealer tier upgraded from Silver to Gold",
    timestamp: "2026-03-08T16:45:00Z",
    dealerName: "Family Leisure",
  },
  {
    id: "a4",
    type: "order",
    description: "Order #CLB-2026-0087 shipped via freight carrier",
    timestamp: "2026-03-08T14:20:00Z",
    dealerName: "Texas Billiards",
  },
  {
    id: "a5",
    type: "warranty",
    description: "Warranty claim #WC-2026-012 resolved, replacement rail shipped",
    timestamp: "2026-03-08T11:00:00Z",
    dealerName: "Peters Billiards",
  },
  {
    id: "a6",
    type: "lead",
    description: "Lead converted to order: Catherine Wells, Scottsdale AZ",
    timestamp: "2026-03-07T15:30:00Z",
    dealerName: "Best Buy Pool Supply",
  },
  {
    id: "a7",
    type: "system",
    description: "Price list updated for Q2 2026, all dealers notified",
    timestamp: "2026-03-07T09:00:00Z",
  },
  {
    id: "a8",
    type: "order",
    description: "Order #CLB-2026-0085 entered production, est. 4 weeks",
    timestamp: "2026-03-06T13:45:00Z",
    dealerName: "All Pro Billiards",
  },
  {
    id: "a9",
    type: "dealer",
    description: "New dealer application received, pending review",
    timestamp: "2026-03-06T10:20:00Z",
  },
  {
    id: "a10",
    type: "lead",
    description: "5 new leads from trade show registration, assigned to territories",
    timestamp: "2026-03-05T17:00:00Z",
  },
];

/* ─── Announcements ─── */

export const adminAnnouncements: AdminAnnouncement[] = [
  {
    id: "ann1",
    title: "Q2 2026 Price Adjustments",
    body: "Effective April 1, select hardwood finishes will see a 3-5% adjustment. Updated price lists are available in the Downloads section. Contact your regional rep for volume pricing.",
    category: "pricing",
    status: "published",
    createdAt: "2026-03-01T09:00:00Z",
    publishedAt: "2026-03-01T09:00:00Z",
    targetAudience: "all",
  },
  {
    id: "ann2",
    title: "New Skylar Collection Launch",
    body: "The redesigned Skylar pool table is now available in three new finishes: Weathered Oak, Espresso, and Driftwood. Sell sheets and photography assets have been uploaded to the portal.",
    category: "product_update",
    status: "published",
    createdAt: "2026-02-20T10:00:00Z",
    publishedAt: "2026-02-22T08:00:00Z",
    targetAudience: "all",
  },
  {
    id: "ann3",
    title: "Platinum Dealer Exclusive: Early Access to 2027 Catalog",
    body: "Platinum tier dealers now have early access to the 2027 product catalog. Preview new collections and provide feedback before the official release.",
    category: "marketing",
    status: "published",
    createdAt: "2026-02-15T14:00:00Z",
    publishedAt: "2026-02-16T09:00:00Z",
    targetAudience: "platinum",
  },
  {
    id: "ann4",
    title: "Shipping Schedule Update: Spring 2026",
    body: "Due to increased demand, lead times for custom finish orders have extended to 6-8 weeks. Standard finishes remain at 3-4 weeks. Plan accordingly for spring deliveries.",
    category: "operations",
    status: "published",
    createdAt: "2026-02-10T11:00:00Z",
    publishedAt: "2026-02-10T11:00:00Z",
    targetAudience: "all",
  },
  {
    id: "ann5",
    title: "Summer Trade Show Schedule",
    body: "Draft announcement for upcoming summer trade show appearances and booth assignments.",
    category: "marketing",
    status: "draft",
    createdAt: "2026-03-08T16:00:00Z",
    targetAudience: "all",
  },
];

/* ─── Analytics: Territory Performance ─── */

export const territoryStats: TerritoryStats[] = [
  { territory: "Houston Metro", dealerCount: 2, totalRevenue: 215600, avgOrderValue: 3850, leadCount: 8, conversionRate: 22.5 },
  { territory: "DFW Metro", dealerCount: 2, totalRevenue: 131100, avgOrderValue: 4097, leadCount: 6, conversionRate: 16.7 },
  { territory: "Central Texas", dealerCount: 1, totalRevenue: 92100, avgOrderValue: 4847, leadCount: 4, conversionRate: 25.0 },
  { territory: "Upper Midwest", dealerCount: 1, totalRevenue: 41300, avgOrderValue: 3754, leadCount: 3, conversionRate: 13.3 },
  { territory: "Southwest", dealerCount: 1, totalRevenue: 28700, avgOrderValue: 3588, leadCount: 2, conversionRate: 10.0 },
  { territory: "Northeast", dealerCount: 1, totalRevenue: 38900, avgOrderValue: 3890, leadCount: 1, conversionRate: 20.0 },
];

/* ─── Analytics: Monthly Revenue ─── */

export const monthlyRevenue: MonthlyRevenue[] = [
  { month: "Oct", revenue: 248000 },
  { month: "Nov", revenue: 312000 },
  { month: "Dec", revenue: 286000 },
  { month: "Jan", revenue: 298000 },
  { month: "Feb", revenue: 321000 },
  { month: "Mar", revenue: 342800 },
];

/* ─── Analytics: Product Performance ─── */

export const productPerformance: ProductPerformance[] = [
  { name: "Skylar", category: "Pool Tables", unitsSold: 42, revenue: 188400 },
  { name: "Elayna", category: "Pool Tables", unitsSold: 38, revenue: 171000 },
  { name: "Addison", category: "Pool Tables", unitsSold: 28, revenue: 112000 },
  { name: "Dutchess", category: "Pool Tables", unitsSold: 22, revenue: 99000 },
  { name: "Piston", category: "Shuffleboards", unitsSold: 15, revenue: 67500 },
  { name: "Skylar Cue Rack", category: "Cue Racks", unitsSold: 35, revenue: 24500 },
  { name: "Hartford Cue Rack", category: "Cue Racks", unitsSold: 28, revenue: 19600 },
  { name: "Premium Ball Set", category: "Accessories", unitsSold: 64, revenue: 12800 },
];
